### ISSUE TITLE
Dataset

### ISSUE THREAD

**Issue by yinloonga** [Shawn207/map_manager#1]
Good job!  
I would like to know if you saved the `bag dataset` when you did the experiment. I would like to see how the code runs in the simulation environment first. If so, would you consider making it **publicly available** for people to test and use.  
Thank you!

**Comment by Shawn207** [comment]
> Good job! I would like to know if you saved the `bag dataset` when you did the experiment. I would like to see how the code runs in the simulation environment first. If so, would you consider making it **publicly available** for people to test and use. Thank you!

Sorry we did not have bag file. For simulation, take gazebo-rviz as an example, just go to cfg/dynamic_map/param.yaml, change line 16-18 to whatever topic your simulator published. Also, modify line 25 to your simulator intrinsics and 27 to your depth_scale_factor

**Comment by yinloonga** [comment]
Ok, thank you very much for your reply, I will try it later. 
Now I close this issue.
